version: "3.9"

services:
  neo4j:
    image: neo4j:5.15
    container_name: neo4j-equipo5
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./data:/data
      - ./logs:/logs
      - ./import:/import
      - ./plugins:/plugins
      - ./conf:/conf
      - ../neo4j:/scripts
    environment:
      NEO4J_AUTH: "neo4j/test123"
      NEO4J_dbms_allow__upgrade: "true"
      NEO4J_server_memory_heap_initial__size: 1G
      NEO4J_server_memory_heap_max__size: 2G
      NEO4J_server_memory_pagecache_size: 1G
    restart: unless-stopped
