services:
  app:
    build: ./app
    container_name: fastapi-neo4j-aura
    environment:
      NEO4J_URI: ${NEO4J_URI:-neo4j+s://257b501e.databases.neo4j.io}
      NEO4J_USER: ${NEO4J_USER:-neo4j}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD:-6euITjyHAIxRU3dtVQHZ5Y9kjKEUNfOMzLUsH3s9IGU}
      NEO4J_DATABASE: ${NEO4J_DATABASE:-neo4j}
    ports:
      - "8000:8000"
    restart: unless-stopped
