services:
  neo4j:
    image: neo4j:5.15
    container_name: neo4j-extra
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "neo4j/test1234"
      NEO4J_server_memory_heap_initial__size: 1G
      NEO4J_server_memory_heap_max__size: 2G
      NEO4J_server_memory_pagecache_size: 1G
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
    volumes:
      - ./neo4j-data/data:/data
      - ./neo4j-data/logs:/logs
      - ./neo4j-data/import:/import
      - ./neo4j-data/plugins:/plugins
      - ./neo4j-data/conf:/conf
      - ../neo4j:/scripts:ro
      - ../data/shopping_behavior.csv:/import/shopping_behavior.csv:ro
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  app:
    build: ./app
    container_name: fastapi-neo4j-app
    depends_on:
      neo4j:
        condition: service_healthy
    environment:
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: test1234
    ports:
      - "8000:8000"
    working_dir: /app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

networks:
  default:
    name: proyecto-extra-net
