version: "3.9"

services:
  neo4j:
    image: neo4j:5.15
    container_name: neo4j-extra
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "neo4j/test123"
      NEO4J_dbms_memory_heap_initial__size: 1G
      NEO4J_dbms_memory_heap_max__size: 2G
      NEO4J_server_memory_pagecache_size: 1G
    volumes:
      - ./neo4j-data/data:/data
      - ./neo4j-data/logs:/logs
      - ./neo4j-data/import:/import
      - ./neo4j-data/plugins:/plugins
      - ./neo4j-data/conf:/conf
      - ../neo4j:/scripts:ro
      - ../data/shopping_behavior.csv:/import/shopping_behavior.csv:ro

  app:
    build: ./app
    container_name: fastapi-neo4j-app
    depends_on:
      - neo4j
    environment:
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: test123
    ports:
      - "8000:8000"
    working_dir: /app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

networks:
  default:
    name: proyecto-extra-net
